global:
  cloudIntegrationEnabled: false
  tls:
    enabled: false
    generateCerts:
      certProvider: cert-manager
      clusterIssuerName: dev-clusterissuer
opensearch:
  tls:
    enabled: false
  securityConfig:
    authc:
      basic:
        username: exampleuser
        password: examplepassword
  securityContextCustom:
    runAsUser: 1000
    fsGroup: 1000
  master:
    persistence:
      storageClass: standard
      size: 10Gi
    resources:
      requests:
        cpu: 600m
        memory: 2Gi
      limits:
        cpu: 900m
        memory: 2Gi
  snapshots:
    enabled: false
    size: 1Gi
    s3:
      enabled: false
      pathStyleAccess: true
  client:
    ingress:
      enabled: true
      hosts:
        - opensearch-opensearch-service
dashboards:
  enabled: true
  ingress:
    enabled: false
    hosts:
      - host: dashboards-opensearch-service
        paths:
          - path: /
dbaasAdapter:
  enabled: false
  dbaasAggregatorPhysicalDatabaseIdentifier: opensearch
  opensearchRepo: snapshots
  opensearchRepoRoot: /usr/share/opensearch/
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
monitoring:
  enabled: false
  includeIndices: true
  slowQueries:
    enabled: true
curator:
  enabled: false
  backupSchedule: 0 * * * *
  evictionPolicy: 0/1d,7d/delete
  username: example
  password: example
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
integrationTests:
  enabled: true
  tags: smokeORopensearch_images
statusProvisioner:
  lifetimeAfterCompletion: 30
  integrationTestsTimeout: 900
  podReadinessTimeout: 900
