# Backend is generated by Atmos (stacks/mixins/azure.yaml)
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
  }
}

# Subscription comes from ARM_SUBSCRIPTION_ID env var
provider "azurerm" {
  features {}
}

locals {
  tags = {
    project    = var.cluster_name
    created-by = "Terraform-CI"
    cost-usage = var.cluster_name
  }
}

resource "azurerm_resource_group" "this" {
  name     = var.cluster_name
  location = var.region
  tags     = local.tags
}

# AKS creates and manages its own VNet
resource "azurerm_kubernetes_cluster" "this" {
  name                = var.cluster_name
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
  dns_prefix          = var.cluster_name
  kubernetes_version  = var.kubernetes_version

  default_node_pool {
    name       = "system"
    node_count = var.node_count
    vm_size    = var.instance_type
  }

  identity {
    type = "SystemAssigned"
  }

  tags = local.tags
}
