# Backend is generated by Atmos (stacks/mixins/azure.yaml)
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
  }
}

# Subscription comes from ARM_SUBSCRIPTION_ID env var
provider "azurerm" {
  features {}
}

locals {
  tags = {
    project    = var.cluster_name
    created-by = "Terraform-CI"
    cost-usage = var.cluster_name
  }
}

resource "azurerm_resource_group" "this" {
  name     = var.cluster_name
  location = var.region
  tags     = local.tags
}

# AKS creates and manages its own VNet
resource "azurerm_kubernetes_cluster" "this" {
  name                = var.cluster_name
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
  dns_prefix          = var.cluster_name
  kubernetes_version  = var.kubernetes_version

  default_node_pool {
    name       = "system"
    node_count = var.node_count
    vm_size    = var.instance_type
    # Lets instance_type changes rotate the pool instead of recreating the cluster
    temporary_name_for_rotation = "tmpsystem"

    # Azure default; declared to avoid a perpetual diff
    upgrade_settings {
      max_surge = "10%"
    }
  }

  identity {
    type = "SystemAssigned"
  }

  tags = local.tags
}

# Static inbound IP for LoadBalancer services (ArgoCD, see stacks/deploy/azure-dev.yaml).
# Lives in the AKS node resource group, so the cluster identity can attach it without extra role assignments.
resource "azurerm_public_ip" "ingress" {
  name                = "${var.cluster_name}-ingress"
  resource_group_name = azurerm_kubernetes_cluster.this.node_resource_group
  location            = azurerm_resource_group.this.location
  allocation_method   = "Static"
  sku                 = "Standard"
  tags                = local.tags
}
