# ============== DEPLOYMENT VARIABLES ============================
CLOUD_TOPOLOGY_KEY: kubernetes.io/hostname
READONLY_CONTAINER_FILE_SYSTEM_ENABLED: false
REPLICA_ROLLING_TIMEOUT_SECONDS: 600
LIVENESS_PROBE_INITIAL_DELAY_SECONDS: 120
REGION_DBAAS: database
NODE_SELECTOR_DBAAS_KEY: region
DBAAS_RECREATE_DEPLOYMENT_STRATEGY: false

# ============== SERVICE VARIABLES ============================
LOG_LEVEL: "INFO"
DBAAS_LOG_LEVEL: "INFO"

DISABLE_DEPRECATED_API: false

PRODUCTION_MODE: true
POSTGRES_HOST: 'pg-patroni.postgresql'
POSTGRES_PORT: '5432'
DBAAS_SECURITY_CONFIGURATION_LOCATION: '/etc/dbaas/security'
DBAAS_PREMATURE_REGISTRATION_ADAPTER_ADDRESSES: ''
DBAAS_DEFAULT_PHYSICAL_DATABASES_DISABLED: false

MEM_ARGS: "-Xms128m -Xmx128m -Xss512k -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -XX:ReservedCodeCacheSize=64M -XX:CompressedClassSpaceSize=32M -XX:MinMetaspaceExpansion=1M -XX:MaxMetaspaceExpansion=8M -XX:CodeCacheExpansionSize=256k -XX:MaxDirectMemorySize=10m -XX:+UseParallelGC -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90"
MEMORY_LIMIT: "520Mi"
CPU_LIMIT: "2"
CPU_REQUEST: "100m"
REPLICAS: 1