apiVersion: "database.arangodb.com/v1"
kind: "ArangoDeployment"
metadata:
  name: arangodb-cluster
spec:
  mode: Single
  image: arangodb/arangodb:3.11.5
  single:
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
  authentication:
    jwtSecretName: None
  tls:
    caSecretName: None