# Backend is generated by Atmos (stacks/mixins/gcp.yaml)
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 8.0"
    }
  }
}

# Project comes from GOOGLE_PROJECT env var
provider "google" {
  region = var.region
}

locals {
  # GCP labels must be lowercase
  labels = {
    project    = var.cluster_name
    created-by = "terraform-ci"
    cost-usage = var.cluster_name
  }
}

resource "google_compute_network" "this" {
  name                    = var.cluster_name
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "this" {
  name          = var.cluster_name
  region        = var.region
  network       = google_compute_network.this.id
  ip_cidr_range = cidrsubnet(var.vpc_cidr, 4, 0)

  secondary_ip_range {
    range_name    = "pods"
    ip_cidr_range = cidrsubnet(var.vpc_cidr, 2, 1)
  }

  secondary_ip_range {
    range_name    = "services"
    ip_cidr_range = cidrsubnet(var.vpc_cidr, 4, 1)
  }
}

resource "google_container_cluster" "this" {
  name                = var.cluster_name
  location            = var.region
  network             = google_compute_network.this.id
  subnetwork          = google_compute_subnetwork.this.id
  min_master_version  = var.kubernetes_version
  deletion_protection = false

  # Node pool is managed separately below
  remove_default_node_pool = true
  initial_node_count       = 1

  ip_allocation_policy {
    cluster_secondary_range_name  = "pods"
    services_secondary_range_name = "services"
  }

  resource_labels = local.labels
}

resource "google_container_node_pool" "this" {
  name       = var.cluster_name
  cluster    = google_container_cluster.this.id
  location   = var.region
  node_count = var.node_count

  node_config {
    machine_type = var.instance_type
    spot         = true
    labels       = local.labels
    oauth_scopes = ["https://www.googleapis.com/auth/cloud-platform"]
  }
}
