name: Install Cloud-Core

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment Name"
        required: false
        default: "dev"

jobs:
  Install-Cloud-Core:
    environment: "${{github.event.inputs.environment}}"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Clone Cloud-Core-Bootstrap
        uses: actions/checkout@v4
        with:
            repository: Netcracker/qubership-core-bootstrap
            path: cloud-core

      - name: Listing downloaded files
        run: |
          pwd
          ls -R cloud-core

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.32.0'

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Verify tools
        run: |
          terraform version
          kubectl version --client
          helm version
          aws --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}

      - name: Configure kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ vars.AWS_REGION || 'us-east-1' }} --name ${{ vars.TF_VAR_EKS_NEW_CLUSTERNAME }}

      - name: Verify cluster access
        run: kubectl get nodes

      - name: Helm install
        run: |
          pwd
          apt update
          apt install make envsubst
          ls ./qubership-rabbitmq/operator/charts/helm/rabbitmq/
          cd ./cloud-core/cloud-core-local-dev
          echo  "Namespace to install Rabbit-MQ: ${{ vars.TF_VAR_CORE_INSTALL_NAMESPACE }}"
          make install CONFIG_FILE=../../cloud-core/local.mk 
          
