name: Install Consul

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment Name"
        required: false
        default: "dev"

jobs:
  Install-Consul:
    uses: ./.github/workflows/_install-helm-component.yml
    permissions:
      contents: read
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      component_name: Consul
      environment: "${{ github.event.inputs.environment }}"
      chart_repo: Netcracker/qubership-consul
      chart_path: charts/helm/consul-service
      values_dir: ./consul
      values_file: example-config.yaml
      release_name: consul-service
      namespace: ${{ vars.TF_VAR_CONSUL_INSTALL_NAMESPACE }}
