name: Install Kafka

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment Name"
        required: false
        default: "dev"

jobs:
  Install-Kafka:
    uses: ./.github/workflows/_install-helm-component.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      component_name: Kafka
      environment: "${{ github.event.inputs.environment }}"
      chart_repo: Netcracker/qubership-kafka
      chart_path: operator/charts/helm/kafka
      values_dir: ./kafka
      values_file: sample.yaml
      release_name: kafka
      namespace: ${{ vars.TF_VAR_KAFKA_INSTALL_NAMESPACE }}
