name: Install Opensearch

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment Name"
        required: false
        default: "dev"

jobs:
  Install-Opensearch:
    uses: ./.github/workflows/_install-helm-component.yml
    permissions:
      contents: read
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      component_name: Opensearch
      environment: "${{ github.event.inputs.environment }}"
      chart_repo: Netcracker/qubership-opensearch
      chart_path: operator/charts/helm/opensearch-service
      values_dir: ./opensearch
      values_file: example-config.yaml
      release_name: opensearch
      namespace: ${{ vars.TF_VAR_OPENSEARCH_INSTALL_NAMESPACE }}
