name: Install Rabbit-MQ

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment Name"
        required: false
        default: "dev"

jobs:
  Install-Rabbit-MQ:
    environment: "${{github.event.inputs.environment}}"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Clone public Rabbit-MQ repo
        uses: actions/checkout@v4
        with:
            repository: Netcracker/qubership-rabbitmq
            path: qubership-rabbitmq

      - name: Listing downloaded files
        run: |
          pwd
          ls -R qubership-rabbitmq

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.32.0'

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Verify tools
        run: |
          terraform version
          kubectl version --client
          helm version
          aws --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}

      - name: Configure kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ vars.AWS_REGION || 'us-east-1' }} --name ${{ vars.TF_VAR_EKS_NEW_CLUSTERNAME }}

      - name: Verify cluster access
        run: kubectl get nodes

      - name: Helm install
        run: |
          pwd
          ls ./qubership-rabbitmq/operator/charts/helm/rabbitmq/
          cd ./rabbitmq
          echo  "Namespace to install Rabbit-MQ: ${{ vars.TF_VAR_RABBIT_INSTALL_NAMESPACE }}"
          echo "Starting Helm install"
          helm install --namespace=${{ vars.TF_VAR_RABBIT_INSTALL_NAMESPACE }} --create-namespace -f ./example-config.yaml rabbitmq-service ../qubership-rabbitmq/operator/charts/helm/rabbitmq/