name: Terraform CI Install PG-Skipper

on:
  workflow_dispatch: # Запуск вручную через UI
    inputs:
      #environment:
      #  description: "Environment (dev/prod)"
      #  required: false
      #  default: "dev"
      tf_command:
        description: "Terraform command"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply

jobs:
  terraform:
    runs-on: ubuntu-latest
    #environment: ${{ github.event.inputs.environment || 'dev' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Clone public pgskipper-operator repo
        uses: actions/checkout@v4
        with:
            repository: Netcracker/pgskipper-operator
            path: pgskipper-operator

      - name: Listing downloaded files
        run: |
          pwd
          ls -R pgskipper-operator

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.32.0'

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Verify tools
        run: |
          terraform version
          kubectl version --client
          helm version
          aws --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}

      - name: Configure kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ vars.AWS_REGION || 'us-east-1' }} --name ${{ vars.EKS_CLUSTER_NAME }}

      - name: Verify cluster access
        run: kubectl get nodes

      - name: Terraform Init and Plan
        env:
          TF_VAR_namespace: ${{ vars.PG_INSTALL_NAMESPACE }}
        run: |
          pwd
          cd ./pg_skipper
          terraform init
          terraform plan
#          terraform apply -auto-approve