name: Install Zookeeper

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment Name"
        required: false
        default: "dev"

jobs:
  Install-Zookeeper:
    uses: ./.github/workflows/_install-helm-component.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      component_name: Zookeeper
      environment: "${{ github.event.inputs.environment }}"
      chart_repo: Netcracker/qubership-zookeeper
      chart_path: operator/charts/helm/zookeeper-service
      values_dir: ./zookeeper
      values_file: example.yaml
      release_name: zookeeper-service
      namespace: ${{ vars.TF_VAR_ZOOKEEPER_INSTALL_NAMESPACE }}
